#The retrieval service uses this GCP service account to connect to VertexAI and CloudSQL.
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.gcpSaName }}-retrieval-secret
data:
  service-account.json: {{ .Files.Get "files/service-account.json" | b64enc }}
type: Opaque
