#Service endpoint for the frontend service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "genai-retrieval-augmented-generation.fullname" . }}-frontend
  labels:
    {{- include "genai-retrieval-augmented-generation-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceFrontend.type }}
  ports:
    - port: {{ .Values.serviceFrontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "genai-retrieval-augmented-generation-frontend.selectorLabels" . | nindent 4 }}
